export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#dee9fc',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-secondary-fixed': '#341100',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        'surface-container': '#e6eeff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-primary-fixed-variant': '#005320',
        'tertiary-fixed': '#ffdcc3',
        'primary-fixed': '#7ffc97',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        primary: '#006b2c',
        'primary-fixed-dim': '#62df7d',
        'inverse-primary': '#62df7d',
        secondary: '#9d4300',
        'surface-tint': '#006e2d',
        'secondary-fixed': '#ffdbca',
        'surface-container-highest': '#d9e3f6',
        'on-primary-fixed': '#002109',
        'secondary-fixed-dim': '#ffb690',
        'tertiary-fixed-dim': '#ffb77d',
        'surface-variant': '#d9e3f6',
        'on-tertiary-fixed': '#2f1500',
        'on-surface-variant': '#3e4a3d',
        'on-error-container': '#93000a',
        'on-primary-container': '#f7fff2',
        'on-secondary-container': '#5c2400',
        'on-surface': '#121c2a',
        'primary-container': '#00873a',
        'inverse-surface': '#27313f',
        outline: '#6e7b6c',
        error: '#ba1a1a',
        'surface-dim': '#d0dbed',
        'outline-variant': '#bdcaba',
        'error-container': '#ffdad6',
        'tertiary-container': '#b15f00',
        'surface-bright': '#f8f9ff',
        'on-background': '#121c2a',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#783200',
        tertiary: '#8d4b00',
        'inverse-on-surface': '#eaf1ff',
        background: '#f8f9ff',
        'secondary-container': '#fd761a',
      },
      spacing: {
        'margin-desktop': '2rem', 'max-content-width': '1200px',
        'gutter-tablet': '1rem', 'margin-tablet': '1.5rem',
        'gutter-mobile': '0.75rem', 'space-md': '1rem',
        'space-2xs': '0.25rem', 'space-2xl': '2rem',
        'space-xl': '1.5rem', 'margin-mobile': '1rem',
        'space-3xl': '3rem', 'space-lg': '1.25rem',
        'space-sm': '0.75rem', 'gutter-desktop': '1.5rem', 'space-xs': '0.5rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'price-lg': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'price-sm': ['15px', { lineHeight: '20px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', '3xl': '1.5rem', full: '9999px' },
    },
  },
  plugins: [],
};